### ISSUE TITLE
No logo

### ISSUE THREAD

**Issue by BudiNverse** [BudiNverse/justbus-rs#1]

**Comment by xypnox** [comment]
Hi, I have made a logo that combines bus and the clock. Here it is:
![Untitled(1)](https://user-images.githubusercontent.com/25076171/67685453-20712f80-f9bb-11e9-830e-952ef091252d.png)


Please provide the location at which I should put the logo.

**Comment by BudiNverse** [comment]
Just put it at root thanks! If possible add it to the top of the README after the main header
